services:
  db:
    image: postgres:13
    env_file:
      - ./.env.test
    ports:
      - "5555:5432"
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 2s
      timeout: 5s
      retries: 10
